'use strict';

let genres = [
			'Blues',
			'Classic Rock',
			'Country',
			'Dance',
			'Disco',
			'Funk',
			'Grunge',
			'Hip-Hop',
			'Jazz',
			'Metal',
			'New Age',
			'Oldies',
			'Other',
			'Pop',
			'R&B',
			'Rap',
			'Reggae',
			'Rock',
			'Techno',
			'Industrial',
			'Alternative',
			'Ska',
			'Death Metal',
			'Pranks',
			'Soundtrack',
			'Euro-Techno',
			'Ambient',
			'Trip-Hop',
			'Vocal',
			'Jazz+Funk',
			'Fusion',
			'Trance',
			'Classical',
			'Instrumental',
			'Acid',
			'House',
			'Game',
			'Sound Clip',
			'Gospel',
			'Noise',
			'AlternRock',
			'Bass',
			'Soul',
			'Punk',
			'Space',
			'Meditative',
			'Instrumental Pop',
			'Instrumental Rock',
			'Ethnic',
			'Gothic',
			'Darkwave',
			'Techno-Industrial',
			'Electronic',
			'Pop-Folk',
			'Eurodance',
			'Dream',
			'Southern Rock',
			'Comedy',
			'Cult',
			'Gangsta Rap',
			'Top 40',
			'Christian Rap',
			'Pop / Funk',
			'Jungle',
			'Native American',
			'Cabaret',
			'New Wave',
			'Psychedelic',
			'Rave',
			'Showtunes',
			'Trailer',
			'Lo-Fi',
			'Tribal',
			'Acid Punk',
			'Acid Jazz',
			'Polka',
			'Retro',
			'Musical',
			'Rock & Roll',
			'Hard Rock',
			'Folk',
			'Folk-Rock',
			'National Folk',
			'Swing',
			'Fast  Fusion',
			'Bebob',
			'Latin',
			'Revival',
			'Celtic',
			'Bluegrass',
			'Avantgarde',
			'Gothic Rock',
			'Progressive Rock',
			'Psychedelic Rock',
			'Symphonic Rock',
			'Slow Rock',
			'Big Band',
			'Chorus',
			'Easy Listening',
			'Acoustic',
			'Humour',
			'Speech',
			'Chanson',
			'Opera',
			'Chamber Music',
			'Sonata',
			'Symphony',
			'Booty Bass',
			'Primus',
			'Porn Groove',
			'Satire',
			'Slow Jam',
			'Club',
			'Tango',
			'Samba',
			'Folklore',
			'Ballad',
			'Power Ballad',
			'Rhythmic Soul',
			'Freestyle',
			'Duet',
			'Punk Rock',
			'Drum Solo',
			'A Cappella',
			'Euro-House',
			'Dance Hall',
			'Goa',
			'Drum & Bass',
			'Club-House',
			'Hardcore',
			'Terror',
			'Indie',
			'BritPop',
			'Negerpunk',
			'Polsk Punk',
			'Beat',
			'Christian Gangsta Rap',
			'Heavy Metal',
			'Black Metal',
			'Crossover',
			'Contemporary Christian',
			'Christian Rock',
			'Merengue',
			'Salsa',
			'Thrash Metal',
			'Anime',
			'JPop',
			'Synthpop',
			'Rock/Pop'
		];

let frameAsoc = {'TALB': 'album',
	'TBPM': 'bpm',
	'TCOM': 'composer',
	'TCON': 'genre',
	'TCOP': 'copyright',
	'TDEN': 'encoding-time',
	'TDLY': 'playlist-delay',
	'TDOR': 'original-release-time',
	'TDRC': 'recording-time',
	'TDRL': 'release-time',
	'TDTG': 'tagging-time',
	'TENC': 'encoder',
	'TEXT': 'writer',
	'TFLT': 'file-type',
	'TIPL': 'involved-people',
	'TIT1': 'content-group',
	'TIT2': 'title',
	'TIT3': 'subtitle',
	'TKEY': 'initial-key',
	'TLAN': 'language',
	'TLEN': 'length',
	'TMCL': 'credits',
	'TMED': 'media-type',
	'TMOO': 'mood',
	'TOAL': 'original-album',
	'TOFN': 'original-filename',
	'TOLY': 'original-writer',
	'TOPE': 'original-artist',
	'TOWN': 'owner',
	'TPE1': 'artist',
	'TPE2': 'band',
	'TPE3': 'conductor',
	'TPE4': 'remixer',
	'TPOS': 'set-part',
	'TPRO': 'produced-notice',
	'TPUB': 'publisher',
	'TRCK': 'track',
	'TRSN': 'radio-name',
	'TRSO': 'radio-owner',
	'TSOA': 'album-sort',
	'TSOP': 'performer-sort',
	'TSOT': 'title-sort',
	'TSRC': 'isrc',
	'TSSE': 'encoder-settings',
	'TSST': 'set-subtitle',
	'TYER': 'year',
	/*
	 * Textual frames (<=2.2)
	 */
	'TAL': 'album',
	'TBP': 'bpm',
	'TCM': 'composer',
	'TCO': 'genre',
	'TCR': 'copyright',
	'TDA': 'date',
	'TDY': 'playlist-delay',
	'TEN': 'encoder',
	'TFT': 'file-type',
	'TIM': 'time',
	'TKE': 'initial-key',
	'TLA': 'language',
	'TLE': 'length',
	'TMT': 'media-type',
	'TOA': 'original-artist',
	'TOF': 'original-filename',
	'TOL': 'original-writer',
	'TOR': 'original-year',
	'TOT': 'original-album',
	'TP1': 'artist',
	'TP2': 'band',
	'TP3': 'conductor',
	'TP4': 'remixer',
	'TPA': 'set-part',
	'TPB': 'publisher',
	'TRC': 'isrc',
	'TRK': 'track',
	'TSI': 'size',
	'TSS': 'encoder-settings',
	'TT1': 'content-group',
	'TT2': 'title',
	'TT3': 'subtitle',
	'TXT': 'writer',
	'TYE': 'year',
	/*
	 * URL frames
	 */
	'WCOM': 'url-commercial',
	'WCOP': 'url-legal',
	'WOAF': 'url-file',
	'WOAR': 'url-artist',
	'WOAS': 'url-source',
	'WORS': 'url-radio',
	'WPAY': 'url-payment',
	'WPUB': 'url-publisher',
	/*
	 * URL frames (<=2.2)
	 */
	'WAF': 'url-file',
	'WAR': 'url-artist',
	'WAS': 'url-source',
	'WCM': 'url-commercial',
	'WCP': 'url-copyright',
	'WPB': 'url-publisher',
	/*
	 * Comment frame
	 */
	'COMM': 'comments',
	'COM': 'comments',
	/*
	 * Image frame
	 */
	'APIC': 'image',
	'PIC': 'image'
};

let imageTypes = [
	'other',
	'file-icon',
	'icon',
	'cover-front',
	'cover-back',
	'leaflet',
	'media',
	'artist-lead',
	'artist',
	'conductor',
	'band',
	'composer',
	'writer',
	'location',
	'during-recording',
	'during-performance',
	'screen',
	'fish',
	'illustration',
	'logo-band',
	'logo-publisher'
];

exports.ID3Genres = genres;
exports.ID3FrameAsoc = frameAsoc;
exports.ID3ImageTypes = imageTypes;
